### ISSUE TITLE
unit of units-parameter in nanometers and not microns?

### ISSUE THREAD

**Issue by haesleinhuepf** [maweigert/biobeam#2]
Hey Martin,

when playing with the method biobeam.focus_field_beam, we had the feeling, that the `units` parameters expects values in nanometers, but according to the documentation, it's microns. Can you clearify?

Thanks,
Robert

**Comment by maweigert** [comment]
units should be all given in microns, so the following should give you the widefield psf on a grid of pixlsize 0.1 um:

`u = focus_field_beam(shape = (128,)*3,units = (.1,)*3, lam = .5, NA = .8)` 

Is that what you want?

**Comment by haesleinhuepf** [comment]
Thanks for the example! I found our bug: We entered the wavelength (lam) in nanometers and that's why the PSF looked so strange! 

Thanks a lot!!

https://github.com/haesleinhuepf/biobeam_examples/blob/master/Advanced_microscopy_course_1.ipynb
