### ISSUE TITLE
opencl version

### ISSUE THREAD

**Issue by gaurav16gupta** [maweigert/biobeam#5]
Hi,
What is the required opencl version? Will it work with OpenCL 1.2?

**Comment by maweigert** [comment]
Hi @gaurav16gupta 
Yes, the current requirement is OpenCL >= 1.2, so it should work...

**Comment by gaurav16gupta** [comment]
Hi @maweigert thanks for the reply. I am also trying to download sample data for light sheet microscopy using Biobeam. The lightsheet_sample_signal.tif download link on [Supplementary Data](https://publications.mpi-cbg.de/publications-sites/6874/) is not working. Please help. Thanks!

**Comment by maweigert** [comment]
Hi, 
the link was indeed broken - thanks for catching that! Should be fixed now...
